name: PHP Syntax Check (Lint)

on:
  push:
    branches: [ "master" ]  # Zmieniono z main na master
  pull_request:
    branches: [ "master" ]  # Zmieniono z main na master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Check PHP Syntax (Lint)
      run: |
        find . -name "*.php" -print0 | xargs -0 -n1 php -l
